services:
  - type: web
    name: telegram-pdf-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 7652247095:AAEciZe1ScwKdMAKazhh1qDGX4Tig_CjnP4
